version: '3'

services:
  app:
    build: .
    depends_on:
      - db
    ports:
      - 8080:80
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./proyect:/var/www/html/
      - ./proyect/composer.json:/var/www/html/composer.json
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    environment: 
      - MYSQL_ALLOW_EMPTY_PASSWORD=True
