name: ci-build

on:
  push:
    branches:
      - dev

env:
  PROJECT_ID: 'webpages-364602'
  GAR_LOCATION: 'us-south1' # TODO: update to your region
  REPOSITORY: 'dev-external' # TODO: update to your Artifact Registry docker repository name
  IMAGE: 'techneek-app'

# TODO: Get data from secrets
jobs:
  setup-build-publish-deploy:
    name: 'Setup, Build, Publish, and Deploy'
    runs-on: 'ubuntu-latest'
    environment: 'development'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v4
      - uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT }}'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: '>= 363.0.0'
      - name: 'Download from GSutil'
        run: |-
          gsutil cp gs://srchach/proyects/techneek/dump.sql ./dump.sql
          gsutil cp gs://srchach/proyects/techneek/.env ./proyect/.env
      - name: Login to GAR
        uses: docker/login-action@v3
        with:
          # TODO: manage GAR_LOCATION
          registry: us-south1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      - name: build-and-push
        run: |-
          DOCKER_TAG="${GAR_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY}/${IMAGE}:${GITHUB_SHA}"
          
          docker build \
            --tag "${DOCKER_TAG}" \
            --build-arg GITHUB_SHA="${GITHUB_SHA}" \
            --build-arg GITHUB_REF="${GITHUB_REF}" \
            .

          docker push ${DOCKER_TAG}
