name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Hello Codelies!
        run: echo "Hello from wf:'${{ github.workflow }}' triggered by the event:'${{ github.event_name }}' done by user:'${{ github.actor }}'"

      - name: More and more!
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: |
          echo "Job Context: $JOB_CONTEXT"
          echo "Donete!"
      
        